"""split scoring reason

Revision ID: 26556066c0a2
Revises: 7f80ec8225ab
Create Date: 2026-03-09 19:07:24.900558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26556066c0a2'
down_revision = '7f80ec8225ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_sub_tasks', sa.Column('round1_reason', sa.Text(), nullable=True))
    op.add_column('video_sub_tasks', sa.Column('round2_reason', sa.Text(), nullable=True))
    op.drop_column('video_sub_tasks', 'scoring_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_sub_tasks', sa.Column('scoring_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('video_sub_tasks', 'round2_reason')
    op.drop_column('video_sub_tasks', 'round1_reason')
    # ### end Alembic commands ###
