"""remove output format and json schema

Revision ID: 4a84e2de9864
Revises: 0041
Create Date: 2026-03-06 18:11:36.203843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a84e2de9864'
down_revision = '0041'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_column('evolink_settings', 'understand_json_schema')
    op.drop_column('evolink_settings', 'understand_output_format')
    op.drop_column('pipeline_settings', 'understand_json_schema')
    op.drop_column('pipeline_settings', 'understand_output_format')
    # upscaling_api_url may not exist on all environments
    op.execute("ALTER TABLE pipeline_settings DROP COLUMN IF EXISTS upscaling_api_url")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_settings', sa.Column('understand_output_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('pipeline_settings', sa.Column('upscaling_api_url', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('pipeline_settings', sa.Column('understand_json_schema', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('evolink_settings', sa.Column('understand_output_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('evolink_settings', sa.Column('understand_json_schema', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
