"""add scoring_reason

Revision ID: 7f80ec8225ab
Revises: a552507cf4d1
Create Date: 2026-03-09 19:03:36.525946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f80ec8225ab'
down_revision = 'a552507cf4d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_generations_account_id', table_name='daily_generations')
    op.drop_index('ix_daily_generations_owner_id', table_name='daily_generations')
    op.drop_index('ix_daily_generations_status', table_name='daily_generations')
    op.drop_index('ix_daily_generations_target_date', table_name='daily_generations')
    op.drop_index('ix_daily_generations_template_id', table_name='daily_generations')
    op.drop_table('daily_generations')
    op.add_column('video_sub_tasks', sa.Column('scoring_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_sub_tasks', 'scoring_reason')
    op.create_table('daily_generations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shots', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('result_videos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('selected_video_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='daily_generations_pkey')
    )
    op.create_index('ix_daily_generations_template_id', 'daily_generations', ['template_id'], unique=False)
    op.create_index('ix_daily_generations_target_date', 'daily_generations', ['target_date'], unique=False)
    op.create_index('ix_daily_generations_status', 'daily_generations', ['status'], unique=False)
    op.create_index('ix_daily_generations_owner_id', 'daily_generations', ['owner_id'], unique=False)
    op.create_index('ix_daily_generations_account_id', 'daily_generations', ['account_id'], unique=False)
    # ### end Alembic commands ###
